title: Purple Cyber Sec
author: Feisty One
email: feistty0ne at gmail com
description: > # this means to ignore newlines until "show_exerpts:"
  Walk with me in this random journey of discovery
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://feisty.one/"
permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Feisty One
  tagline: Cyber Security | Threat Hunter
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  # generate social links in footer
  social_links:
    twitter: feisTTY0x1
    github:  famedfeya
    #linkedIn: in/famed
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
  navigation:
  # - title: Resume
  #   url: "/resume"
    - title: 'Home'
      url: /
    - title: 'About'
      url: /about
    - title: 'Archives'
      url: /archives
    - title: 'Miscellanous'
      url: /misc
    - title: 'Portfolio'
      url: /misc
    - title: 'Presentations'
      url: /presentations
    - title: 'Blog'
      url: /blog
    - title: 'Workshops'
      url: /workshops
# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
    provider:
    statcounter:
        sc_project  :
        sc_security :
        sc_invisible: 1
        sc_text     : 2
    google:
        tracking_id: ''
    getclicky:
      site_id:
    mixpanel:
        token: ''
    piwik:
        baseURL: '' # Piwik installation address (without protocol)
        idsite: ''  # the id of the site on Piwik

# Build settings
remote_theme: thelehhman/plainwhite-jekyll


# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
    provider:
    disqus:
      short_name:
    livefyre:
      site_id:
    intensedebate:
      account:
    facebook:
      appid:
      num_posts: 5
      width: 580
      colorscheme: light

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
